import type { PrayerSchedule } from '@/types/prayer-schedule';

export const mockHorarios: PrayerSchedule[] = [
  {
    id: 'h1',
    title: 'Santa Misa',
    days: 'Lunes a viernes',
    time: '9:00 h',
    location: 'Iglesia principal',
    type: 'Misas',
    isActive: true,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'h2',
    title: 'Santa Misa',
    days: 'Sábados',
    time: '19:00 h',
    location: 'Iglesia principal',
    type: 'Misas',
    isActive: true,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'h3',
    title: 'Santa Misa',
    days: 'Domingos',
    time: '12:00 y 20:00 h',
    location: 'Iglesia principal',
    type: 'Misas',
    isActive: true,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'h4',
    title: 'Confesión',
    days: 'Martes y jueves',
    time: '18:00 – 19:00 h',
    location: null,
    type: 'Sacramentos',
    isActive: true,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'h5',
    title: 'Confesión',
    days: 'Sábados',
    time: '18:00 – 19:00 h',
    location: null,
    type: 'Sacramentos',
    isActive: true,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'h6',
    title: 'Adoración al Santísimo',
    days: 'Primeros viernes de mes',
    time: '17:00 – 19:00 h',
    location: 'Capilla interior',
    type: 'Cultos',
    isActive: true,
    createdAt: '',
    updatedAt: '',
  },
  {
    id: 'h7',
    title: 'Catequesis infantil',
    days: 'Sábados',
    time: '10:30 – 12:00 h',
    location: 'Sala de catequesis',
    type: 'Formación',
    isActive: true,
    createdAt: '',
    updatedAt: '',
  },
];
